version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: appsec-postgres-dev
    environment:
      POSTGRES_USER: appsec_user
      POSTGRES_PASSWORD: appsec_password
      POSTGRES_DB: appsec_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - appsec-network

  # Development Application (with hot reload)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: appsec-dashboard-dev
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://appsec_user:appsec_password@postgres:5432/appsec_dashboard
      - SESSION_SECRET=dev-secret-key
    ports:
      - "3000:5000"
    depends_on:
      - postgres
    networks:
      - appsec-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_dev_data:

networks:
  appsec-network:
    driver: bridge